server:
  port: 9000

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://8.140.229.190:3306/yumi_dms_v1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useInformationSchema=true&remarks=true&tinyInt1isBit=false&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&allowMultiQueries=true&autoReconnect=true&autoReconnectForPools=true&autoReconnectForPools=true&autoReconnectForP
    username: yumi
    password: j5ciTEhZ3pJE4WY3
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: off